"use client";

// import type { Metadata } from "next";
import "../globals.css";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { PAGES } from "@/constants/constants";
import PageLoader from "@/components/page-loader";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { saveNewUser } from "@/lib/auth";
import DashboardHeader from "@/components/dashboard-header";

// export const metadata: Metadata = {
//   title: "Home ~ Valse",
//   description: "Generated by create next app",
// };

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      refetchInterval: 10000,
    },
  },
});

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const [loading, setLoading] = useState(true);
  const { push } = useRouter();

  useEffect(() => {
    const data = localStorage.getItem("spotify_auth_data");

    if (!data) {
      push(PAGES.auth);
      return;
    }

    const { access_token, expires_at } = JSON.parse(data);
    const date_ms = new Date().getTime();

    if (date_ms >= expires_at) {
      localStorage.removeItem("spotify_auth_data");
      push(PAGES.auth);
      return;
    }

    saveNewUser(access_token);

    setLoading(false);
  }, [push]);

  return (
    <>
      <QueryClientProvider client={queryClient}>
        <main className="[--header-height:calc(theme(spacing.14))] flex items-center justify-center p-6">
          {loading ? (
            <PageLoader fullScreen />
          ) : (
            <div className="w-full max-w-5xl flex items-center justify-center flex-col gap-6">
              <DashboardHeader />
              {children}
            </div>
          )}
        </main>
      </QueryClientProvider>
    </>
  );
};

export default RootLayout;
